In [1]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [2]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

In [3]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

In [4]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [5]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [6]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [7]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [8]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [9]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [11]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

In [12]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [13]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

In [14]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [15]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [16]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [17]:
x=2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [19]:
x=50
seq(0,x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [20]:
x= seq(1,50,1/2)

In [22]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

In [24]:
x=c(9,8,7,6)
ind = seq(along=x)
ind

[1] 1 2 3 4

In [25]:
x[ind[2]]

[1] 8

In [27]:
Sys.time()

[1] "2026-09-03 04:15:16 UTC"

In [28]:
Sys.Date()

[1] "2026-09-03"

In [30]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [31]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [33]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [34]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [35]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [36]:
letters                 # lowercase alphabet sequence

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [38]:
letters[1:3]

[1] "a" "b" "c"

In [39]:
letters[3:1]

[1] "c" "b" "a"

In [40]:
letters[21:23]

[1] "u" "v" "w"

In [41]:
letters[2]

[1] "b"

In [42]:
LETTERS                 # uppercase alphabet sequence

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [43]:
LETTERS[1:3]

[1] "A" "B" "C"

In [44]:
LETTERS[3:1]

[1] "C" "B" "A"

In [45]:
LETTERS[2]

[1] "B"

In [47]:
help("rep")

In [49]:
rep(3.5, times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

In [50]:
rep(1:4, 2)

[1] 1 2 3 4 1 2 3 4

In [52]:
x = 1:4
x

[1] 1 2 3 4

In [53]:
rep(x, times = 3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

In [54]:
rep(x, each =3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [55]:
rep(1:4,each = 2)

[1] 1 1 2 2 3 3 4 4

In [56]:
rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [57]:
rep(1:4, times = 3, each = 2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [58]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [59]:
ans = seq(from=2, to=8, by=2)
ans

[1] 2 4 6 8

In [60]:
rep(1:4, ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

In [62]:
x = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [63]:
rep(x,3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [64]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [65]:
rep(c("apple", "banana", "cake"), 2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

In [68]:
rep(2, length = 5)

[1] 2 2 2 2 2

In [69]:
rep(c(2, 3), length = 5)

[1] 2 3 2 3 2

In [70]:
rep(c(2, 3, 4), length = 5)

[1] 2 3 4 2 3

In [71]:
rep("apple", length = 5)

[1] "apple" "apple" "apple" "apple" "apple"

In [72]:
rep(c("a", "b", "c"), length = 2)

[1] "a" "b"

In [73]:
rep(c("a", "b", "c"), length = 5)

[1] "a" "b" "c" "a" "b"

In [74]:
y = c(8, 5, 7, 6)
y

[1] 8 5 7 6

In [75]:
sort(y)

[1] 5 6 7 8

In [76]:
sort(y, decreasing = TRUE)

[1] 8 7 6 5

In [77]:
y = c(9,8,5,7,6)
y

[1] 9 8 5 7 6

In [78]:
order(y)

[1] 3 5 4 2 1

In [79]:
order(y,decreasing = TRUE)

[1] 1 2 4 5 3

In [80]:
mode(2.432)

[1] "numeric"

In [81]:
mode(c(3, 4, 5, 6, 7, 8))

[1] "numeric"

In [82]:
mode("India")

[1] "character"

In [83]:
mode(c("India" , "Canada"))

[1] "character"

In [84]:
mode(factor(c("UP", "MP")) )

[1] "numeric"

In [85]:
mode(factor(c("UP", "MP")))

[1] "numeric"

In [86]:
mode(list("India", "USA"))

[1] "list"

In [87]:
mode(data.frame(x = 1:2, y = c("India", "USA")))

[1] "list"

In [88]:
mode(print)

[1] "function"

In [89]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = TRUE)
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [90]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [91]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [92]:
x1[2,1] = "hello"

In [95]:
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [97]:
x1 + x2

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [98]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = TRUE)
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [99]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [100]:
matlist = list(x1, x2)

In [101]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [104]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [105]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [106]:
z1 = list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(data = 5:8, nrow = 2, ncol = 2, byrow = TRUE)
)
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [107]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [108]:
z1[[1]][2]

[1] "juice"